### ISSUE TITLE
No connection could be made because the target machine actively refused it 

### ISSUE THREAD

**Issue by ben555** [Microsoft/PowerBI-CSharp#10]
I get this error with the PBIWebApp. What am I doing wrong?

**Comment by wbreza** [comment]
Can you please provide more information on the API that you are calling?

**Comment by binay567** [comment]
please check with your network team, it does not work inside an organisation network. It works fine in public network, so you can try at home.

**Comment by wbreza** [comment]
Let us know if you are still experiencing this issue.
