### ISSUE TITLE
Need a sample showing how to use Datasets.PostRows()/PostRowsAsync()

### ISSUE THREAD

**Issue by danield72** [Microsoft/PowerBI-CSharp#105]
I really don't know whether this is the correct place to post this or not.  If it's not, could someone please point me to the correct forum?

My question:  The documentation at https://docs.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.v1.datasetsextensions.postrowsasync?view=powerbiapi-1.1.10 fails to explain what the requestMessage parameter (of type Object) is supposed to contain.

The farthest I've been able to get throws a Microsoft.Rest.HttpOperationException; its Response.Content shows code = ItemNotFound, and message = "Dataset [xxx] is not Push API dataset.".

I know the dataset ID is at least exists ("[xxx]" in the sample response above) as it matches one of the datasets I can successfully enumerate.  At this point however I'm not even sure if this is because the value I provide for requestMessage is valid or not.  All other params are pretty straightforward.

I've tried to pass in the following string, literally, with no additional change, which is from sample I had found elsewhere; that sample goes directly to the REST API.  While the columns the JSON string defines don't match the table in my dataset, I wouldn't expect it to complain about the ID of the dataset I pass in as not being a "Push API dataset", whatever that means.  I get the same results whether I use the string below, or handcraft something else that matches my actual columns.

Can I at least assume I'm doing the right thing by passing in this JSON string for the requestMessage param?  Or is it expecting something else altogether?

string rowsJson = "{\"rows\":" +
"[{\"ProductID\":1,\"Name\":\"Adjustable Race\",\"Category\":\"Components\",\"IsCompete\":true,\"ManufacturedOn\":\"07/30/2014\"}," +
"{\"ProductID\":2,\"Name\":\"LL Crankarm\",\"Category\":\"Components\",\"IsCompete\":true,\"ManufacturedOn\":\"07/30/2014\"}," +
"{\"ProductID\":3,\"Name\":\"HL Mountain Frame - Silver\",\"Category\":\"Bikes\",\"IsCompete\":true,\"ManufacturedOn\":\"07/30/2014\"}]}";

**Comment by ali-hamud** [comment]
for the requestMessage parameter you need to pass a dynamic C# object.
if you succeed, please insert a sample here. you may get to it before I write the sample as I am busy with other tasks.

**Comment by ali-hamud** [comment]
ok, here is a code sample:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-walkthrough-push-data-complete-code/
