### ISSUE TITLE
Provision a new workspace failed,shows an invalid status code 'forbidden'

### ISSUE THREAD

**Issue by 826612865** [Microsoft/PowerBI-CSharp#107]
i want to provision a workspace on my workspace collection.
![image](https://user-images.githubusercontent.com/29538991/27783835-63266676-600a-11e7-8e23-2142c0652536.png)
i down load the azure samples.
https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/
followed the steps in the document 
https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/

![image](https://user-images.githubusercontent.com/29538991/27783991-fc0f83d6-600a-11e7-8313-f0e6c3b25501.png)
 i've renewed  NuGET package and i cannot figure it out.

Any help is much appreciated!

**Comment by ali-hamud** [comment]
I am afraid we don't have this Request ID any more in our logs.
can you please repro this again and send us a new request Id to investigate?

**Comment by ali-hamud** [comment]
closing as no response.
please re-open if this problem persist.
