### ISSUE TITLE
The type or namespace name 'IdentityModel' does not exist in the namespace 'Microsoft' 

### ISSUE THREAD

**Issue by ben555** [Microsoft/PowerBI-CSharp#11]
The sample doesn't compile. I don't have Microsoft.IdentityModel.Clients.ActiveDirectory in my GAC. Should this reference be changed to a NuGet package reference?

**Comment by dvana** [comment]
Which sample?

Also, please install the IdentityModel package

Install-Package Microsoft.IdentityModel
