### ISSUE TITLE
Links to the sample in doc are dead

### ISSUE THREAD

**Issue by Dumbeldor** [Microsoft/PowerBI-CSharp#111]
Hi,

The links to the sample int the documentation are dead: https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-report-register/

Thanks.

**Comment by noanu** [comment]
Thank you for letting us know!
We will fix it ASAP.

**Comment by ali-hamud** [comment]
please reopen if it doesn't work for you.
