### ISSUE TITLE
Beta API are they alive and useful?

### ISSUE THREAD

**Issue by Maqsoodp** [Microsoft/PowerBI-CSharp#112]
What happened to Beta API are they still valid? 

My code is old written during preview days using following library
Microsoft.PowerBI.Api.1.0.12-preview
Microsoft.PowerBI.Core.1.0.12-preview

With the above preview libs I get bad request when I call them using
**client.Imports.PostImportWithFileAsync**

Some of the public methods used in Core like 
 **PowerBIToken**.**CreateProvisionToken** are no more in V1 or V2 . This is used in the preview libs to get token before I could create new workspace as below -
**client.Workspaces.PostWorkspaceAsync(workspaceCollectionName);**

how to get them in the V1 or V2?
Can you share a link or documentation that details the diff between V1 and V2 version of latest libs?

**Comment by ali-hamud** [comment]
Hi, as I understand, you work with Power BI in azure workspaces. right?
Api.V2 works with the new embedded story - using Power BI account and power bi portal not azure.
Token generation moved from client app code to our services. now, there is an API to generate embed token.
for more info:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/

If you want to use the API.V1 with your current solution, you can do that. it will be deprecated within a year I think.
