### ISSUE TITLE
No API to update connectionstring for a dataset in a group?

### ISSUE THREAD

**Issue by nickraphael** [Microsoft/PowerBI-CSharp#115]
There does seem to be an area of the API missing.  To call client.Gateways.UpdateDatasourceAsync, we need to get a gateway to get to an Exponent and a Modulus.  However, the gatewayId returned from client.Datasets.GetGatewayDatasourcesInGroupAsync does not seem to be a real gateway.  

There is a discussion here:
https://community.powerbi.com/t5/Developer/Possible-to-update-credentials-via-REST-API/td-p/137509/highlight/true/page/2

Is anyone actively monitoring this list of issues?

**Comment by RanDidi** [comment]
Hi nickraphael,
For datasources that aren't working through on-prem gateway (e.g. SQL Azure), no encryption is required for the credentials on UpdateDatasourceRequest which is passed to UpdateDatasourceAsync.
Depending on the datasource type - the value of 'credentials' have different formats, e.g. for SQL - the value of credentials is a JSON structure with the following schema:
{"credentialData":[  
    { "value":"<ActualUserName>", "name":"username" },
    {  "value":"<ActualPassword>", "name":"password" } 
]}

**Comment by nickraphael** [comment]
Thanks - I'll give that a try.  Is this documented anywhere?

**Comment by RanDidi** [comment]
It's missing from our official documentation, we are working on getting it properly documented.
