### ISSUE TITLE
The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by bdelaney** [Microsoft/PowerBI-CSharp#12]
using the sample app 'embed-a-tile-into-an-app' after already setting up and using 'get-started-web-app-asp.net'
I use the first button to login to PowerBI. Works and my token is displayed. Now try to use 'getDashboardsButton_Click' and the 401 error is returned. I do see in debug that the token is being passed into the 'getDashboardsButton_Click' and to get this far I must have already added the clientID and Key correctly. The samples have not been changed other than using the settings to add the required bits of info. I set up the Azure App permissions following the process at 'Register an Application for Power BI' and since it worked for the first sample app, 'get-started,' figured it would then work in second.
what am I missing?

**Comment by dvana** [comment]
Please try https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-register-a-web-app/ to register the app, and use a client id and client secret.
