### ISSUE TITLE
Bad request when refreshing dataset through API

### ISSUE THREAD

**Issue by johnlop** [Microsoft/PowerBI-CSharp#120]
When I call the refresh method it fails and I get:

> Operation returned an invalid status code 'BadRequest'

This is the line (no problem with the client configuration since I am able to load my reports and tiles):
`object result = await client.Datasets.RefreshDatasetInGroupAsync(groupId, datasetId);`

The group ID and dataset ID are the ones I see in app.powerbi.com when on the dataset:
![2017-08-29 12_03_49-power bi](https://user-images.githubusercontent.com/18294057/29831153-372c57a4-8cb2-11e7-8edb-3c271f5e1d1e.png)

Any idea?

**Comment by masters3d** [comment]
I wonder if this happens when you account runs out of refreshes.

**Comment by diklab** [comment]
Hi @johnlop 
Is this issue still happening for you?

Thanks,
Dikla

**Comment by ali-hamud** [comment]
Closing as no response from customer.
btw, this could happen if you call refresh API on DirectQuery Model.
