### ISSUE TITLE
How to get access token for 'myworkspace' ?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/PowerBI-CSharp#121]
I want to display a report present in **'myworkspace'**

this is the code in HomeController.cs
`var reports = await client.Reports.GetReportsInGroupAsync(GroupId);`
which I've changed to 
`var reports = await client.Reports.GetReportsAsync();`

The above works fine and fetches all the reports .The next line where the groupid is used is 
` var generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view");`                
`var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);`
which I changed to 
`var generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view");`
`var tokenResponse = await client.Reports.GenerateTokenAsync(report.Id, generateTokenRequestParameters);`

This is where I'm getting an error as 

**Operation returned an invalid status code 'Forbidden'**

How do I display a report that is present in my **'myworkspace'** workspace ?

**Comment by johnlop** [comment]
Why did you change `GenerateTokenInGroupAsync` to `GenerateTokenAsync`?

**Comment by nupurkamble** [comment]
@johnlop because I want to generate a token and I don't have a group because I don't have a pro account. I want to display a report that is present in the 'myworkspace' workspace.

**Comment by johnlop** [comment]
I'm not 100% certain but I think that Power BI embedded requires a Pro account with a dedicated workspace: 

> Note:
> Power BI Premium is not required for development of your application. The developers of the application will need to have a Power BI Pro license.

https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding-content/

**Comment by nupurkamble** [comment]
@johnlop Oh. Okay i guess I'll have to get a pro account then. Anyway thanks a lot!

**Comment by ali-hamud** [comment]
To use groups you need a pro license.
Power BI capacity is not required for development of your application. The developers of the application will need to have a Power BI Pro license.
To go to production, you need to buy a capacity.
