### ISSUE TITLE
"Not Found" exception with nameConflict: "Overwrite" in PostImportWithFileAsyncInGroup

### ISSUE THREAD

**Issue by alshort** [Microsoft/PowerBI-CSharp#122]
My struggles with `PostImportWithFileAsyncInGroup` continue. (See Issue #104 for the other issue I have with it).

I was initially under the assumption that the nameConflict parameter specifies a policy to follow in the event that a naming conflict occurs. Unfortunately, when calling `PostImportWithFileAsyncInGroup()` with `nameConflict: "Overwrite"` with a named file (that doesn't currently exist in the workspace/group I'm posting to), I get "`Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'`". Setting it to "Ignore" fixes the issue, but I don't think this is the correct behaviour as this is predicated upon you knowing the state of the import beforehand.

So is this erroneous or expected behaviour? Is this an issue that could be addressed in this library, or is it a problem with the actual REST endpoint itself?

**Comment by nicksav** [comment]
I would treat it as a bug, but the work around is to check if report already exists. 
`
                        List<Report> reports = (await client.Reports.GetReportsInGroupAsync(workspaceId)).Value as List<Report>;
                        if (reports.Where(report => report.Name == datasetName).Any())
                            overwrite = true;

                        var import = await client.Imports.PostImportWithFileAsyncInGroup(workspaceId, fileStream, datasetName, overwrite ? "Overwrite" : null);
`

**Comment by ali-hamud** [comment]
This behavior is by design.
please pass Overwrite only if you know that the file exists. otherwise, pass Ignore.

**Comment by BennyM** [comment]
From a user perspective it really would be better if it wouldn't fail when the argument gets passed in. Design or not.

**Comment by masters3d** [comment]
I agree with @BennyM  here but the SDK is only following what the REST API is doing. 
In my code, I am checking to see if something exist then changing it to "Ignore" if there nothing to override. 

"Ignore" is a bad name for this. But that is what they API is using so this repo must use the same naming. 

In my use facing app, I changed this to instead be called "Replace". Funny that this is the same terminology that the Powerbi Desktop app uses.

**Comment by BennyM** [comment]
@masters3d indeed, yet this is the only place we can voice our ideas :)
