### ISSUE TITLE
Request for token with included Roles returns nothing - RLS

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-CSharp#123]
Request for token with included Roles returns nothing if Power BI book has no roles created. 
Before, no matter what we put in the ticket (in terms of roles), if pbix model didnt have them, it just will show all.

Is it how it has been designed this time?
I understand as work around we have to create all possible roles inside pbix model to enable all access?

Thanks
Nick

**Comment by eligr** [comment]
Hi Nick!
For PBIX without any roles, use the GenerateTokenInGroupAsync API without any effective identities
If you have any roles in the PBIX, and you want to see all data, create a role without any filters and use it in generate token.

You can also see if your existing datasets require effective identity/roles using GetDatasetsInGroup API, and looking at the IsEffectiveIdentityRequired and IsEffectiveIdentityRolesRequired properties.

Eli.
