### ISSUE TITLE
Generate one token for all tiles

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-CSharp#124]
Guys, I am not sure if it is actually possible from design perspective as Tiles can be from different reports. 
But currently I have 20 tiles in the SAAS app. It means that for me to display 20 of those I have to call 20 times get Token api to generate 20 tokens for each tile. It is really bad in terms of performance...
Any clue here?

**Comment by gregorybor** [comment]
Yes. If you have 20 tiles, you will have to call get token 20 times. But if all your tiles are from the reports of the same workspace, then you can embed a dashboard and pin your visuals to this dashboard. Thus you will only call getToken once.
