### ISSUE TITLE
Dataset.Tables is always null

### ISSUE THREAD

**Issue by hson89** [Microsoft/PowerBI-CSharp#126]
Hi everyone,

I'm trying to get the access to the tables inside a dataset. I managed to get access to the dataset however the when I use dataset.Tables it always returns null.  I also tried to use Datasets.GetTables and passed my dataset ID however it returned "Operation returned an invalid status code 'NotFound'" while with the same Dataset ID, I can get the dataset successfully. Below is my code.
`using (var client = new PowerBIClient(new Uri(Data.PBIRestURI), tokenCredentials))
            {
                var dataset = client.Datasets.GetDatasetById("My Dataset ID");
            }`
Can someone give me a hint on what I did wrong here please? I'm developing it with as Window App 
Thank you in advance.
Son

**Comment by masters3d** [comment]
The dataset only returns what the API would return for the same call. 
If you want the tables you have to make another API call using:

```
    var tablesObject  =   client.Datasets.GetTables(datasetKey: id)

```

Then you can get the actual tables by

```
tablesObject.Value
```

**Comment by diklab** [comment]
Hi @hson89, 
The answer you got from masters3d should resolve your issue.

Thanks,
Dikla
