### ISSUE TITLE
When Creating Data Set, defaultRetentionPolicy is not set correctly

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-CSharp#130]
Guys, when Creating a new Data Set and setting defaultRetentionPolicy, the SDK puts it under body, where the specs saying it has to be part of the queryString parameter:
https://msdn.microsoft.com/en-us/library/mt186545.aspx

**Comment by diklab** [comment]
Hi @nicksav,
The specs are correct, the retention policy is set by the queryString parameter (if missing default policy will be used) and not by the property under the body.

Thanks,
Dikla
