### ISSUE TITLE
Cannot add user to app workplace as "Member", only as "Admin"

### ISSUE THREAD

**Issue by TedPattison** [Microsoft/PowerBI-CSharp#133]
I can add a new user to a newly created app workspace as "Admin" but it fails when I try and add a new user to an app workspace as "Member"

PowerBIClient pbiClient = GetPowerBiClient();

GroupCreationRequest request = new GroupCreationRequest("AWS04");
Group aws = pbiClient.Groups.CreateGroup(request);

GroupUserAccessRight user1Permissions = new GroupUserAccessRight("Admin",  "JasonB@pbibc.onMicrosoft.com");
pbiClient.Groups.AddGroupUser(aws.Id, user1Permissions);

GroupUserAccessRight user2Permissions = new GroupUserAccessRight("Member", "jamesb@pbibc.onMicrosoft.com");
// this always fails with Bad Request
pbiClient.Groups.AddGroupUser(aws.Id, user2Permissions);

**Comment by diklab** [comment]
Currently you can only add admin users via this API.
https://msdn.microsoft.com/en-us/library/mt784677.aspx
