### ISSUE TITLE
Supporting Dedicated Capacity Management

### ISSUE THREAD

**Issue by alshort** [Microsoft/PowerBI-CSharp#135]
At the moment, you can manage dedicated capacity for a workspace collection through the Azure portal (manually), are there any plans to support doing this per-workspace in this SDK?

I know that this project only reflects the state of the REST API, of which I can't find documentation relating to dedicated capacity of workspaces, is there any news of this being brought in?

**Comment by diklab** [comment]
Hi,
You used the "workspace collection" which is the old embedded solution, whereas the creating Power BI Embedded/Dedicated capacity via azure portal is our new solution (there is not workspace assignment via azure portal) - can you please clarify what is the solution you are asking about?

Thanks,
Dikla
