### ISSUE TITLE
Add a workspace to dedicated capacity

### ISSUE THREAD

**Issue by tdraganidis** [Microsoft/PowerBI-CSharp#136]
In powerbi.com, there's the advanced option to turn on the `Dedicated Capacity` for a specific workspace (Edit workspace -> Advanced).
Is there a way to do the same programmatically?

**Comment by eligr** [comment]
Hi Thanos!
In SDK version 2.0.10 we added AssignToCapacity method on the Groups object.

Eli.

**Comment by tdraganidis** [comment]
Great news, @eligr! Thanks!
