### ISSUE TITLE
API missing a couple useful fields in Dashboard and Dataset entities

### ISSUE THREAD

**Issue by t-val** [Microsoft/PowerBI-CSharp#139]
I have come across a couple of fields missing in the API that would be useful to my application.

1) The Dataset object should return a list of Role names if roles are present.
2) The Dashboard object should return a list of DatasetIds.  

Any reason why these couldn't or shouldn't be returned?  Am I missing another way to get at this data?

Thanks.

**Comment by eligr** [comment]
Hello!

1. This is currently not supported
2. You can use the dashboards/<id>/tiles API to get the datasets, https://msdn.microsoft.com/en-us/library/mt465741.aspx

Hope this helps!

Eli.

**Comment by t-val** [comment]
Well 1 out of 2 ain't bad. Thanks @eligr  for pointing me in the right direction.

Tony
