### ISSUE TITLE
o connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by binay567** [Microsoft/PowerBI-CSharp#14]

**Comment by wbreza** [comment]
Can you please provide more information on the API that you are calling?

**Comment by binay567** [comment]
My redirect URI is :  http://localhost/PBIWebApp/Redirect.aspx
The below piece of code is giving the error.
 AuthenticationResult AR = AC.AcquireTokenByAuthorizationCode(code, new Uri(redirectUri), cc);
