### ISSUE TITLE
Unable to LOAD PBIX by use simple 

### ISSUE THREAD

**Issue by bettialessandro** [Microsoft/PowerBI-CSharp#16]
Hi ,
I'm new on BI , I download your example to create Embedded  from an existing .pbix file .
All registration key exc. is done when i try to applicate menu 6 the demo answer me access deny .
1) Try to open Visual Studio as administrator .
2) Give to .pbix file path NEWTWORK , IUSR and NEWTWORK SERVICE r/w grant .
 
How can i send the .pibx file to Azure ? I miss something .
Any help is appreciate .

Thank you 
Alex

**Comment by wbreza** [comment]
You can find detailed steps to get started with the sample @ https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/

Hope this helps.

**Comment by bettialessandro** [comment]
Hi Thank you for answer ,
Already done all step in the example .. the C# code stop when i try to make point 6 of example .
Ask PBIX file i gave file name and path .. but tell me access deny ... no solution for that there is some one use it with success ?

Thank you 
Alex

**Comment by wbreza** [comment]
Do you have the PBIX file open in Power BI Desktop when you attempt to upload the file?  Power BI Desktop will put a lock on the file so no other program is able to read it.  

If that is the case ensure that you put the full absolution file path into the command line tool.

**Comment by bettialessandro** [comment]
Hi , 
PBI Desktop Close - sorry to borrow you with so silly issue ... my file name is Giacenza_Valore.pbix 
and path is : C:\Progetti\PowerBI 

Is it correct ?

**Comment by wbreza** [comment]
OK - If the data above is accurate then you should enter: C:\Progetti\PowerBI\Giacenza_Valore.pbix when the tool prompts you for the file.

If you continue to have file access issues try moving the file to a location where you can confirm your account has read access.
