### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by aranm** [Microsoft/PowerBI-CSharp#18]
How long until we see the PowerBI SDK being open sourced? This repo has been around a while and I'd love to grab the powerBI stuff and make it work against the .net core but where is the code?

**Comment by wbreza** [comment]
The code will be published soon.  In the meantime here is a swagger file that can be used to generate a custom client SDK in whichever languages you prefer.

You can learn more about Swagger @ [swagger.io](http://swagger.io)

**Swagger file**
[swagger.txt](https://github.com/Microsoft/PowerBI-CSharp/files/245961/swagger.txt)

**Comment by aranm** [comment]
How long is soon?

**Comment by wbreza** [comment]
SDKs are now available.
