### ISSUE TITLE
Tile embedding sample: Bad request error at sign-in.

### ISSUE THREAD

**Issue by jeroenterheerdt** [Microsoft/PowerBI-CSharp#2]
I ran the PBIWebApp.Embed solution and got an error on step 1 (sign in): Sorry, but we’re having trouble signing you in. 
We received a bad request.

Am I missing something here?

**Comment by dvana** [comment]
Hello, did you register the app and set your client id and secret key in web.config?

**Comment by wesback** [comment]
I'm having the same issue, I did configure my client id & secret key.

**Comment by wesback** [comment]
Ok, I've added my localhost redirect URL to the application in my Azure AD Application and now it seems to work.

**Comment by dvana** [comment]
Thanks, I'll make sure we are clear about the redirect url

Sent from my Windows Phone
________________________________

**Comment by wesback** [comment]
Both Jeroen and myself are on the Microsoft tenant, not sure if that complicates things ;-)

**Comment by dvana** [comment]
Should work fine on Microsoft tenant.
