### ISSUE TITLE
PBIWebApp - Index out of range

### ISSUE THREAD

**Issue by philipplenz** [Microsoft/PowerBI-CSharp#20]
Hello, 

when I run the PowerBI Web APP (PBIWebApp) Solution I run into this error (see attachment)
![exception](https://cloud.githubusercontent.com/assets/19327789/15269633/77a44132-1a05-11e6-9dfb-c0fa1cc45428.PNG)

Does anayone a hint for me?

Tanks in advance!

**Comment by wbreza** [comment]
Let us know if you are still experiencing this issue.
