### ISSUE TITLE
View Report in Windows Forms

### ISSUE THREAD

**Issue by IshamMohamed** [Microsoft/PowerBI-CSharp#23]
Hi, 

Is there a way to list Power BI Reports or Tiles to Windows Forms? I can list the reports and when I try to load the report using the URL listed in the JSON file, I get the attached error if I use the default Web brower control in Visual Studio. 

![image](https://cloud.githubusercontent.com/assets/2231923/16550668/58c464fc-41cb-11e6-9c80-a30554108147.png)

But if I use Chrome control, I ended up on an endless loading animation.

**Comment by wbreza** [comment]
It looks like the web browser control you are using within your application does not support `requestAnimationFrame`  This API was been available in IE 10+ and is required for embedding Power BI reports.  Take a look at [caniuse](http://caniuse.com/#search=requestanimationframe) for compatibility for this API.
