### ISSUE TITLE
Operation returned an invalid status code 'Forbidden' 

### ISSUE THREAD

**Issue by donquijotedelamancha** [Microsoft/PowerBI-CSharp#24]
I was able to embed a PowerBI report in a web app with the PowerBI.API.Beta Package but with the PowerBI.API.V1 I only get "Forbidden" when trying to GetReports().

My code is: 

PowerBIToken devToken = PowerBIToken.CreateReportEmbedToken(workspaceCollection, workspaceId, myReportId, DateTime.Now.AddHours(2));

(the previous version didn't require myReportId, here I am supplying the friendly name with which I provisioned the workspace)

Then I am doing:
IPowerBIClient client = this.CreatePowerBIClient(devToken);
ODataResponseListReport reportsResponse = client.Reports.GetReports(this.workspaceCollection, this.workspaceId);

This is the step at which I only get "Forbidden" error.

**Comment by wbreza** [comment]
Did you upgrade all your Nuget packages?  The `dev` token has been has been deprecated in favor of a passing in your accessKey directly when calling into the REST api client.

Take a look at our [updated sample](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/master/EmbedSample/Controllers/DashboardController.cs#L69).  You can now pass your access key from your Azure Power BI Workspace collection

**Comment by donquijotedelamancha** [comment]
Thanks a lot for the prompt answer and the link to the example. This allows me to continue working.
I had updated to the latest nuget version but my code was still based on the beta (https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/)
