### ISSUE TITLE
Loading an assembly required for interactive user authentication failed.

### ISSUE THREAD

**Issue by underwater** [Microsoft/PowerBI-CSharp#25]
just tried the PBIGettingStarted (console app) and got this error 
`--- Power BI REST API examples ---
Press Enter key to create a Dataset in Power BI:

Loading an assembly required for interactive user authentication failed. Make sure assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms, Version=2.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' exists`

**Comment by underwater** [comment]
apologies, nuget had failed to get the required .dll (file name too long), due to many nested folders.... shortening the solution path resolved the issue.

**Comment by wbreza** [comment]
Good to hear :)
