### ISSUE TITLE
How to know Import successfully or not

### ISSUE THREAD

**Issue by rosslyn-cuongle** [Microsoft/PowerBI-CSharp#27]
When I call:
   
     var import = await client.Imports.PostImportWithFileAsync(workspaceCollectionName, workspace.WorkspaceId, fileStream, datasetName);

Sometimes, it failed silently. So, I would like to know the above method is successful or not., but I am not sure which property I need to check.

I see `ImportState` on `Import` class but I don't know the value of it when the importing is failed, or even when I tried to debug, it returns `null` when importing is successful.

**Comment by wbreza** [comment]
Take a look at our [provision sample](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/master/ProvisionSample/Program.cs#L443) where we are using this same API.  

In your example the `import` variable should not be null.

**Comment by rosslyn-cuongle** [comment]
Thanks for pointing out, I see, even we use `await` keyword, it does not mean the import is successful or not.

We need to use `while` loop to check import state until the state is `Succeeded`. That's why I randomly got the import failed but I don't know what the reason is.
