### ISSUE TITLE
Newtonsoft.Json Dependancy

### ISSUE THREAD

**Issue by AshleyMedway** [Microsoft/PowerBI-CSharp#28]
The code is dependant on Newtonsoft 7.0.1 but there is no dependency in the NuGet package.

See error below:

>error CS1705: Assembly 'Microsoft.PowerBI.Api, Version=1.1.1.16190, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by wbreza** [comment]
We will take a look.  As a workaround, you can update your local Newtonsoft dependency to 7.0.0.

**Comment by AshleyMedway** [comment]
Yeah I was just working on a very old project, updated and everything is fine. :smile:
