### ISSUE TITLE
Compilation trouble with AcquireTokenByAuthorizationCode method

### ISSUE THREAD

**Issue by oysconsultores** [Microsoft/PowerBI-CSharp#29]
Hi.

We're are trying this sample for some reports we have and we're not able to compile the application because of AcquireTokenByAuthorizationCode method of AuthenticationContext class.

The message is:

_Error	CS1061	'AuthenticationContext' does not contain a definition for 'AcquireTokenByAuthorizationCode' and no extension method 'AcquireTokenByAuthorizationCode' accepting a first argument of type 'AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)_

The version of the Microsoft.IdentityModel.Clients.ActiveDirectory compilation is 3.13.1 of July 26, 2106.

Any help?

Thanks.

**Comment by wbreza** [comment]
We have several samples available in the `samples` folder.  Please let us know which you are having the issue with.

**Comment by oysconsultores** [comment]
We are trying with samples\webforms\integrate-report-web-app.

**Comment by wbreza** [comment]
Looks like you updated the `Microsoft.IdentityModel.Clients.ActiveDirectory` package from what was checked into the `web.config` file.  There were breaking changes introduced in 3.x that have not been incorporated into this sample as of yet.  Please continue on with the checked-in 2.x version

**Comment by oysconsultores** [comment]
Ok, perfect!

Thanks.
