### ISSUE TITLE
Sign in 

### ISSUE THREAD

**Issue by anthonymagann** [Microsoft/PowerBI-CSharp#3]
Error

Additional technical information: Correlation ID: f1281ec2-4e09-41e6-8847-3acfd3eb7922 Timestamp: 2015-12-04 22:48:58Z AADSTS65005: The client application has requested access to resource 'https://analysis.windows.net/powerbi/api'. This request has failed because the client has not specified this resource in its requiredResourceAccess list.

**Comment by dvana** [comment]
Hi, did you register the sample app in Azure and set Permissions to other applications to View all Reports (preview)?

**Comment by anthonymagann** [comment]
I created the app,and allowed all. Still fails. I tried on both the company azure account and created a personal one at it failed to. Try both variations of the code and nether worked. 




Kind Regards,
 
Anthony Magann

**Comment by dvana** [comment]
Okay, let me think through some other possibilities.

**Comment by anthonymagann** [comment]
Thanks for that it's appreciated. I did not see power bi come in permission list in azure commimg to think  of it. Even when clicked show all apps.

**Comment by dvana** [comment]
I haven't forgotten about this. Did you get this resolved?

**Comment by anthonymagann** [comment]
Yes sorry, I meant to close it, this solved it https://dev.powerbi.com/apps
