### ISSUE TITLE
It's necessary a custom Azure Active Directory (AAD) tenant?

### ISSUE THREAD

**Issue by oysconsultores** [Microsoft/PowerBI-CSharp#31]
Hi.

It's required to work with this Power BI samples to own a custom Azure Active Directory (AAD) tenant?

**Comment by wbreza** [comment]
The Power BI service depends on AAD user authentication so you would need to have access to create an Azure AD application on a custom tenant.  If you do not have a tenant you can register for a free Azure trial which you can then use to try out the sample.

**Comment by SmarterKey** [comment]
ye but it is not necessary to have AAD/365 corporate environment.....you can just test it from a personal user level....with your own bespoke non corporate email user account.....me@notGoogle.com......I believe....correct me if i am wrong....

**Comment by wbreza** [comment]
It requires an AAD tenant to register your client application.

**Comment by SmarterKey** [comment]
ok.....but i managed to test the API without.........must have been development only or higher up the stack.....good to know. Thks.

**Comment by wbreza** [comment]
It all depends on how you generate the token to call the APIs.  To call the SaaS apis you can borrow a token from your logged in Power BI session and call into the various APIs.  To call the APIs from your own application you need to register your app with powerbi and use the client ID.

On the Power BI Embedded side on Azure you can call the APIs directly with your Azure access key.
