### ISSUE TITLE
AuthenticationContext in ADAL 3.x no longer has method AcquireToken

### ISSUE THREAD

**Issue by DisplayMonkey** [Microsoft/PowerBI-CSharp#32]
Same goes true with AcquireTokenSilent.

After downloading the sample and updating all NuGet packages comiling the project fails with errors:

Error	7	'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' does not contain a definition for 'AcquireToken' and no extension method 'AcquireToken' accepting a first argument of type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)	E:\project\PowerBI-CSharp\samples\consoleapp\getting-started-for-dotnet\PBIGettingStarted\PBIGettingStarted\Program.cs	552	37	PBIGettingStarted

Error	8	'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' does not contain a definition for 'AcquireTokenSilent' and no extension method 'AcquireTokenSilent' accepting a first argument of type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)	E:\project\PowerBI-CSharp\samples\consoleapp\getting-started-for-dotnet\PBIGettingStarted\PBIGettingStarted\Program.cs	557	37	PBIGettingStarted

**Comment by wbreza** [comment]
Don't upgrade to 3.x of the ADAL nuget package.  It includes breaking changes that are not compatible with the sample.  Please use the lastest available 2.x version of the ADAL package.

**Comment by DisplayMonkey** [comment]
OK, thanks

**Comment by dhawalHub** [comment]
I am VS 2013 and installed Nuget 2.12.0.817 and getting the same issue above. do I need to update to newer VS ? anything else I can do to fix?

**Comment by dhawalHub** [comment]
never mind. fixed the issue.
"C:\PBIGettingStarted\packages\Microsoft.IdentityModel.Clients.ActiveDirectory.3.13.5\lib\net45\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"

Change this to
"
Assembly Microsoft.IdentityModel.Clients.ActiveDirectory
    C:\PBIGettingStarted\packages\Microsoft.IdentityModel.Clients.ActiveDirectory.2.12.111071459\lib\net45\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
"

**Comment by aarunananth** [comment]
Just degrade the ADAL package to 2.x version.

**Comment by larsJoakimNilsson** [comment]
But the interesting question is how to make the PowerBI Authentication work with ADAL 3.x.
Is it possible?

**Comment by zhll2046** [comment]
Use the AcquireTokenAsync in ADAL 3.0

` //string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;

            string token =authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUri), new PlatformParameters(0)).Result.AccessToken;`

**Comment by ConnectedReasoning** [comment]
wbreza... fist bump

**Comment by soberams** [comment]
How to AcquireTokenSilent or AcquireToken when the tenant is "common" (Multi-tenant) ? it gives this error : _**No tenant-identifying information found in either the request or implied by any provided credentials**_. We were able to do this refresh token successfully when we used AcquireRefreshToken. **Please help.**
