### ISSUE TITLE
What's Resource uri to the Power BI resource to be authorized

### ISSUE THREAD

**Issue by oysconsultores** [Microsoft/PowerBI-CSharp#33]
Hi again.

We have trouble with this value.

We constantly get messages when autenticated like _The application named xxxx was not found in the tenant named antoniofernandezbi.onmicrosoft.com. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant._ or _The client application has requested access to resource 'xxxxx'. This request has failed because the client has not specified this resource in its requiredResourceAccess list._

What's the value it expect with the resource BI value?

       var @params = new NameValueCollection
            {
                //Azure AD will return an authorization code. 
                {"response_type", "code"},

                //Client ID is used by the application to identify themselves to the users that they are requesting permissions from. 
                //You get the client id when you register your Azure app.
                {"client_id", _clientID},

                //Resource uri to the Power BI resource to be authorized
                //The resource uri is hard-coded for sample purposes
                {"resource", ????????????????????????????????????},

                //After app authenticates, Azure AD will redirect back to the web app. In this sample, Azure AD redirects back
                //to Default page (Default.aspx).
                { "redirect_uri", _redirectUri}
            };

Thanks in advance.

**Comment by wbreza** [comment]
The Power BI resource uri is `https://analysis.windows.net/powerbi/api`
