### ISSUE TITLE
return Microsoft.AspNet.Mvc.Rendering.HtmlString in extenisons

### ISSUE THREAD

**Issue by jordiruiz** [Microsoft/PowerBI-CSharp#34]
I think that to be valid in MVC 6 could return Microsoft.AspNet.Mvc.Rendering.HtmlString and not mvchtmlstring in @Html.PowerBIReportFor

**Comment by druttka** [comment]
If we change the return type of the `ReportExtensions` and `TokenExtensions`, I'd prefer to go a step further and declare the return type as the `IHtmlString` interface. The class constructed is an implementation detail and should not be relevant to the caller. I am about to open a PR that shows what this would look like.

However, before making the change, we should discuss that it's potentially breaking for any consumers who might be doing the following:
`MvcHtmlString foo = htmlHelper.PowerBIReport("myReport", this.viewModel.Report);`

This seems highly unlikely as well as trivial to resolve, so I wouldn't be opposed to it.
