### ISSUE TITLE
iFrame doesn't load

### ISSUE THREAD

**Issue by DisplayMonkey** [Microsoft/PowerBI-CSharp#36]
Playing with "embed-a-tile-into-an-app" sample (running into the same issue with "integrate-tile-web-app"). I can get all the way to Step 5, where you paste the Tile embed URL from the box in step 4 then click Embed Tile. I never get the iframe.onload post back, and apparently nothing gets loaded into the iframe. Trying this in IE11 (compatibility view setting turned off). When I examine the iframe using the built-in IE dev tool, I can see that the src property receives correct URL, yet nothing gets loaded in to it. Any ideas?

**Comment by wbreza** [comment]
Did you register a client ID and plug in the client id and secret into the sample?  If you need to register an app go to [Register a Power BI App](https://dev.powerbi.com/apps).  

Are you getting any error messages either on the server side or client side?  I was able to run through the sample without any issues.

I was able to run the sample without any issues.

**Comment by DisplayMonkey** [comment]
Yes, apparently, I did register clientid/secret, and updated webconfig in the sample accordingly. Since I can get all the way to step #4, you can figure the OAuth and some PBI APIs (get datasets, tiles, etc.) are already working fine. It's the iFrame that doesn't get populated with anything only. No errors. What else can I check?

**Comment by DisplayMonkey** [comment]
I failed to mention that the tile itself looks great when I view/author it on PBI web site.

**Comment by DisplayMonkey** [comment]
BTW, thanks for your reply, although I don't see why would you close my issue - apparently it still doesn't work for me and you didn't offer any recommendation as to how to solve it...

**Comment by wbreza** [comment]
What value are you putting into the last textbox in Step 5?  The texbox expects the absolute embed url for the tile, not the tile ID or name.

**Comment by DisplayMonkey** [comment]
the embedded url I'm pasting is this:

https://app.powerbi.com/embed?dashboardId=a2d4fd66-8143-4774-b5b7-d9e1d92d9ac1&tileId=01f56ea6-6c6e-414b-926d-0532e5da9060

**Comment by DisplayMonkey** [comment]
Thank you for looking into this and I will appreciate anything that will help me uncover what am I possibly doing wrong...

**Comment by wbreza** [comment]
If you add a breakpoint in the JavaScript [here](https://github.com/Microsoft/PowerBI-CSharp/blob/master/samples/webforms/embed-a-tile-into-an-app/PBIWebApp/Site.Master#L90), is it hit after you add the embed url from step 5?

**Comment by DisplayMonkey** [comment]
No, I don't hit the breakpoint in there. I have even put the alert() statement right at the top of the postActionLoadTile() function and it didn't get called. I did some more playing and, should I replace the iframe.src url with something like bing.com, then indeed the postActionLoadTile() gets called. It's just when the src points to PBI url with dashboard and tile nothing ever returns back..

**Comment by wbreza** [comment]
You can try that.  Looks like for some reason it is not loading the url into the iframe.  Are you seeing a "spinner" at in the middle of the iframe?  Are you behind any firewall or similar that would block powerbi from loading?

**Comment by DisplayMonkey** [comment]
Should I directly navigate to the embed URL (above) in a new browser window/tab I get the scrolling symbol in the middle of the screen, yet nothing else. However in the embedded iframe i don't get anything at all, it just sits blank.

**Comment by DisplayMonkey** [comment]
I'm trying this from work today. Alas, I did the same yesterday from home (no sites filtering) with the same outcome... But with other PBI APIs working, I can't see how it could be a firewall issue..

**Comment by wbreza** [comment]
OK - please verify if you hard code a public URL like (bing.com) into the iframe if it loads.

**Comment by DisplayMonkey** [comment]
I just forced [this line](https://github.com/Microsoft/PowerBI-CSharp/blob/master/samples/webforms/embed-a-tile-into-an-app/PBIWebApp/Site.Master#L82) to "http://bing.com" and then the iframe renders fine and get alert() popup from postActionLoadTile() method.

**Comment by wbreza** [comment]
What happens when you put your `embedUrl` from your post above directly into a new browser window.  You should see a `spinner` in the center of the page.

**Comment by DisplayMonkey** [comment]
That's right, as I mentioned before, I do get the spinner, yet nothing else.. the sipper just sits there.

**Comment by wbreza** [comment]
Can you please capture a fiddler trace of the issue.  It sounds like the embed url is not returning in the iframe which sounds odd.  After you capture the trace please email it to me at wabreza@microsoft.com.

**Comment by DisplayMonkey** [comment]
OK, will do, many thanks for your help and time.

**Comment by DisplayMonkey** [comment]
Hi, working on it right now. The bizarre thing is that it works from jsfiddle, just not from the BI sample. I’m trying to localize the issue right now.

Here’s the fiddle link:

http://jsfiddle.net/kdu42kc7/16/

Thanks // Denis

**Comment by DisplayMonkey** [comment]
I have further examined the network trace in IE11 built-in dev tool for PBI embedded URL:


As you can see it’s pending all the time.

Here’s the same trace should I use Bing for the iframe src:


I tried a secure website just to weed out chance of possible HTTPS vs HTTP (although this particular site complaints that it won’t lend itself into an iframe window, well, at least I get some response):


Something is wrong with PBI server response – it never responds to PBI sample app. Any idea why?
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/PowerBI-CSharp","title":"Microsoft/PowerBI-CSharp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg&quot;,&quot;avatar_image_url&quot;:&quot;https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&quot;,&quot;action&quot;:{&quot;name&quot;:&quot;Open">https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open</a> in GitHub","url":"https://github.com/Microsoft/PowerBI-CSharp&quot;}},&quot;updates&quot;:{&quot;snippets&quot;:[{&quot;icon&quot;:&quot;PERSON&quot;,&quot;message&quot;:&quot;@wbreza">https://github.com/Microsoft/PowerBI-CSharp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wbreza</a> in #36: Can you please capture a fiddler trace of the issue.  It sounds like the embed url is not returning in the iframe which sounds odd.  After you capture the trace please email it to me at mailto:wabreza@microsoft.com">wabreza@microsoft.com</a>."}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/PowerBI-CSharp/issues/36#issuecomment-238295078&quot;}}">https://github.com/Microsoft/PowerBI-CSharp/issues/36#issuecomment-238295078"}}</a>}

**Comment by wbreza** [comment]
Worked with @DisplayMonkey offline and restarting his PC fixed the issue.  It's likely to be a weird quick with IE 11 and/or Windows.

**Comment by dhawal16** [comment]
Hi,

Power BI Report Server Embed is an issue with IE-11 while using it in SharePoint, though it is working with Chrome. While trying F12 in IE by changing the Document mode it started working. How to fix this issue?
