### ISSUE TITLE
Could not load type 'System.IdentityModel.Tokens.JwtSecurityToken' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127

### ISSUE THREAD

**Issue by rbmanian75** [Microsoft/PowerBI-CSharp#38]
Getting the error

Could not load type 'System.IdentityModel.Tokens.JwtSecurityToken' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   at Microsoft.PowerBI.Security.PowerBIToken.Generate(String accessKey)   at 

when i use the latest packages for identitymodel.

**Comment by wbreza** [comment]
There was a breaking change in 5.x of the Jwt library that is not compatible with the Power BI SDK.  Please revert to 4.x till we update our package.  Let us know if this doesn't fix the issue.

**Comment by rbmanian75** [comment]
Thank you for the reply. I revert back to 4.x and it works.

**Comment by wbreza** [comment]
Closing and create #39 to track this enhancement.

**Comment by rolandkru** [comment]
When we revert back to 4.x PowerBI would work, but then OpenIdConnect does not work anymore in our project since it uses 5.x. Is there any timeframe when this will be fixed?

**Comment by pablovianini** [comment]
News?
