### ISSUE TITLE
Report loading stuck

### ISSUE THREAD

**Issue by PascalCeccaldi** [Microsoft/PowerBI-CSharp#4]
Hello,

When I use the sample about the reports, the loading in the Iframe  never ends.
Is this a current issue ?

Thanks

**Comment by Dodge1350** [comment]
I have the same issue... I was able to determine that if I broke on the javascript code that renders the iFrame that I would get the image but if I let the script run straight through without a break, it would just spin and never load... hope that helps with debug.

**Comment by wbreza** [comment]
Can you provide some additional information?  A screenshot or check to see if there are any errors in the browser console.

**Comment by MWaser** [comment]
Using Microsoft Edge on Windows 10

Upon clicking Embed Tile, it hangs on loading & Developer's console says:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Default
HTML1300: Navigation occurred.
Default
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Default
SCRIPT7015: Setting withCredentials attribute for synchronous XMLHttpRequest is deprecated
Default
SCRIPT5007: Unable to get property 'error' of undefined or null reference
data.min.js (4,19363)

**Comment by wbreza** [comment]
We're in the process of udpating these samples to consume our new SDKs. For the time being I would recommend taking a look at the SDKs that we recently released to support Power BI Embedded on Azure.

https://github.com/Microsoft/PowerBI-JavaScript
https://www.nuget.org/profiles/powerbi
https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/

The sample referenced above consumes the ASP.NET SDKs to embed Power BI reports into your web apps.  These were tailored specifically for Power BI Embedded but they are also supported on the Power BI service by passing in the report embed url and access token.

If you want a more vanilla implementation you can choose to work directly with the JavaScript SDK which removes a lot of the complexity of dealing with the iframes and encapsulates the required JavaScript to render the reports.

**Comment by MWaser** [comment]
Hopefully a really stupid question but . . . . is there some special variant of publishing a tile before embedding it?  I mean, as long as you can find the tile though the API, it should be able to be embedded, shouldn't it?  I note that the embed URL is not the same as the API REST URL so . . . . I hope I haven't missed a step and been banging my head for nothing . . . .

**Comment by MWaser** [comment]
Argh!  This is *really* frustrating.  I've reverted back to a static web page with the token quickly hard-coded before I try.  When I use someone else's sample tile with their token (can be grabbed from a website), it is fine.  When I use my sample tile with my token, from a website that is successfully using the API, it is hanging on loading -- until the token expires, at which point I get the expected forbidden.

It seems to me as if the problem HAS to be with the embedded URL server (or, my missing a step of publishing to it . . . . but then one would think that it would fail and give a 404 like it gives a 403 when the token expires).

Any thoughts?

**Comment by MWaser** [comment]
With the static file, I'm receiving exactly the same error.

SCRIPT5007: Unable to get property 'error' of undefined or null reference
data.min.js (4,19363)

Is it possible that my tile doesn't have some necessary variable set?

**Comment by MWaser** [comment]
OK.  Someone has now debugged the problem over at 
http://community.powerbi.com/t5/Developer/Some-embedded-tiles-doesn-t-load-others-load-fine/m-p/28072

Apparently *all* newly created tiles will not embed because they are lacking three critical internal fields.

Is anyone here capable of harassing the Microsoft PowerBI team about this?

**Comment by wbreza** [comment]
Let us know if you are still experiencing this issue.
