### ISSUE TITLE
CreateReportEmbedToken constructor do not add username and role when passed

### ISSUE THREAD

**Issue by glondono** [Microsoft/PowerBI-CSharp#45]
When using Microsoft.PowerBI.Security.PowerBIToken.CreateReportEmbedToken with username and roles as parameters, is not adding the corresponding claims in the token. 

To reproduce
1. Generate token using constructor with username and roles
2. Paste token on jwt.io
3. username and roles properties are not in the token as needed [here](https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-rls) 

Calling the embed visualization return 401 as result.

Thanks

**Comment by FlorisVerhoeven** [comment]
Did you ever fix this? I am facing the same issue.
