### ISSUE TITLE
Add CreatedDateTime and UpdatedDateTime properties to the Import object

### ISSUE THREAD

**Issue by mikeblakeuk** [Microsoft/PowerBI-CSharp#46]
The Import object in NuGet 1.1.3 is missing the CreatedDateTime and UpdatedDateTime properties
![image](https://cloud.githubusercontent.com/assets/1986660/18748028/5a53f5c6-80c8-11e6-8d1c-9bead095736a.png)

Please update the swagger and generate/publish.
https://github.com/Microsoft/PowerBI-CSharp/blob/master/sdk/swagger.json#L844

Thanks

**Comment by mikeblakeuk** [comment]
@dvana ?

**Comment by alihamud** [comment]
I will add this to my tasks.
Thank you.

**Comment by mikeblakeuk** [comment]
Fixed in 2.0.0. Thanks
