### ISSUE TITLE
RefreshSession does not work with PromptBehavior

### ISSUE THREAD

**Issue by skymanaditya1** [Microsoft/PowerBI-CSharp#5]
I have been trying to use Power BI rest API calls in a Console Application. The PromptBehavior class only has Always, Never and Auto methods associated with it. There is no Refresh Session method .

**Comment by dvana** [comment]
It should have Refresh. Please try Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory

**Comment by skymanaditya1** [comment]
Thanks. It worked. 

The traditional way of installing nuget package did not seem to work for some reason (right click on the references and installing the package).

On the other hand, the command Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory from the Package Manager Console worked.
