### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by fasikk** [Microsoft/PowerBI-CSharp#51]
Hi 

I am not able to run get-started-web-app-asp.net\PBIWebApp.sln 

Getting below login failed error.

Sorry, but we’re having trouble signing you in. 
We received a bad request.
 
****************************
Sorry, but we’re having trouble signing you in. 
We received a bad request.

Additional technical information: 
Correlation ID: a41b717b-b40a-4f89-af3c-a7c70cb04671 
Timestamp: 2016-10-31 17:47:06Z 
AADSTS90014: The request body must contain the following parameter: 'client_id'.**** 
 

Regards

**Comment by noanu** [comment]
Hi,

You probably forgot to configure the sample app with the Client Id and the Client Secret:
1.  Please see here how to get the Client Id and the Client Secret: https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-tile-register/#configure-sample
2. After you get them, please use them in the Web.config file under the "applicationSettings" tag like this:
  <applicationSettings>
    <PBIWebApp.Properties.Settings>
      <setting name="ClientID" serializeAs="String">
        <value>{the client Id you received}</value>
      </setting>
      <setting name="ClientSecret" serializeAs="String">
        <value>{the Client Secret you received}</value>
      </setting>
    </PBIWebApp.Properties.Settings>
  </applicationSettings>

If this doesn't solve your problem, please open a new issue.

Thanks and good luck,

Noa
