### ISSUE TITLE
Generate PowerBIToken fails when referencing System.IdentityModel.Tokens.Jwt 5.0

### ISSUE THREAD

**Issue by somnathmr** [Microsoft/PowerBI-CSharp#55]
I have reference to System.IdentityModel.Tokens.Jwt 5.0 in web application. I need the 5.0 version for open id connect authentication. But because of this following powebi code 

PowerBIToken embedToken = PowerBIToken.CreateReportEmbedToken("my collection", "my report id");
string jwt = embedToken.Generate(CommonSettings.AccessKey);

is throwing an exception:
<<<<<
Additional information: Could not load type 'System.IdentityModel.Tokens.JwtSecurityToken' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>>>>>

I believe this is because Microsoft.PowerBI.Core has some dependency on System.IdentityModel.Tokens.Jwt (4.0.2.206221351).

Is there a fix or workaround wherein I can generate the powerbitoken with latest version of System.IdentityModel.Tokens.Jwt?

**Comment by MedAnd** [comment]
This PR might be of interest: [https://github.com/Microsoft/PowerBI-CSharp/pull/49]

**Comment by adam-nagle-customreg** [comment]
Any idea when we can expect a fix for this issue?

**Comment by SebastianGuerreroCardenas** [comment]
Can someone comment on any progress on this?

**Comment by sm-dgdgeng** [comment]
A good workaround is to use BindingRedirect.

**Comment by wind-rider** [comment]
Check out the source for the the powerbi nuget package and manually update the nuget references.

Actually other people did it already and made a pull request, but it never got merged and so it contains old code and I decided to do it myself. It is not the most user friendly way but it works.

It is a pity that the support from Microsoft is lacking in general. There are a lot of issues for common use cases that seem ignored (like this issue or like asp.net
Core 2.0 support) where @ali-hamud could help as he seems to be the main developer; unfortunately there is no direct message functionality on github.

**Comment by ali-hamud** [comment]
There are no plans to update Microsoft.PowerBI.Core as it not needed any more after we moved from Azure Workspace Collection to Power BI Embedded.
Please consider moving to the new way of embedding powerbi, where you will have more features. To do so, please follow the link:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/

Please pay attention that "Non-Interactive" sign-in doesn't work in .Net core. For this yet, we will keep the following issue opened:
#116
