### ISSUE TITLE
Support WorkspaceCollection creation

### ISSUE THREAD

**Issue by xabikos** [Microsoft/PowerBI-CSharp#57]
The SDK so far doesn't support the creation of workspace collection. Is it a deliberate choice or it's something that will come? This is something we need for our project in order to automate the provision of the collections from the code. The only option to do this is the sample provided [here](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app) but we would prefer to do that through the SDK as the other operations.

Thanks for the feedback.

**Comment by ali-hamud** [comment]
This call works with different authentication type.

So, we have another Nuget for it:
https://www.nuget.org/packages/Microsoft.Azure.Management.PowerBIEmbedded/

Nuget source code:
https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/PowerBIEmbedded

After installing the nuget, Please search and use this method:

System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Azure.Management.PowerBIEmbedded.Models.WorkspaceCollection>> CreateWithHttpMessagesAsync(string resourceGroupName, string workspaceCollectionName, Microsoft.Azure.Management.PowerBIEmbedded.Models.CreateWorkspaceCollectionRequest body, [System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null], [System.Threading.CancellationToken cancellationToken = null])

    Member of Microsoft.Azure.Management.PowerBIEmbedded.IWorkspaceCollectionsOperations

**Comment by ali-hamud** [comment]
Sorry for the late response btw.
