### ISSUE TITLE
unable to call API using service account

### ISSUE THREAD

**Issue by back5576** [Microsoft/PowerBI-CSharp#6]
Hi,

I changed the web sample to use login directly instead of interactively using the following code

`
            string authority = String.Format("https://login.microsoftonline.com/{0}", Properties.Settings.Default.TenantID);

            AuthenticationContext authenticationContext = new AuthenticationContext(authority);

            ClientCredential credential = new ClientCredential(clientId: Properties.Settings.Default.ClientID, clientSecret: Properties.Settings.Default.ClientSecretKey);

            AuthenticationResult result = authenticationContext.AcquireToken(resource: "https://analysis.windows.net/powerbi/api", clientCredential: credential);
`
based upon samples I found online. But when I run it I get a "403 Forbidden".  It does return a key, but listing datasets throws a WebException.

I need it to run non-interactively because it is a scheduled refresh task.

**Comment by pankajdhillon** [comment]
In AccessToken method by changing this line I was able to connect non-interactively
token = authContext.AcquireToken(resourceUri, clientID, userCredential).AccessToken;

**Comment by back5576** [comment]
Are you getting a ClientCredential the same was as was my code?

**Comment by back5576** [comment]
Sorry, just noticed that you presumably used UserCredential class rather than ClientCredential. I was hoping to have this work using a service account (clientid and client secret) rather than a username and password.

**Comment by wbreza** [comment]
Let us know if you are still experiencing this issue.
