### ISSUE TITLE
Report not refreshing automatically

### ISSUE THREAD

**Issue by pankajdhillon** [Microsoft/PowerBI-CSharp#8]
using this code I am able to add rows to my dataset but report doesn't reflect new data until I manually refresh it in power BI, is something missing here to make report real time like shown in this video https://www.youtube.com/watch?v=ORp9omvtjdY%22

**Comment by wbreza** [comment]
@jocaplan

**Comment by wbreza** [comment]
Let us know if you are still experiencing this issue.
