### ISSUE TITLE
powerbi.js reference  in _layouts'cshtml

### ISSUE THREAD

**Issue by jaiswati** [Microsoft/PowerBI-CSharp#87]
Hi 

added the powerbi.js reference  in _layouts'cshtml.
<script src="@Url.Content("~/js/powerbi.js")"></script>

When  I run the webapp in  IISexperess mode , this js was referenced correctly
but when  I run webapp in Local IIS ( Project Properties -- > Web -- > Local IIS)
 powerbi.js is not referenced  at all.. (alert added to this js file was not  called )

Please help

**Comment by ali-hamud** [comment]
Hi,
have you managed to solve this issue?
