### ISSUE TITLE
Dotnet core

### ISSUE THREAD

**Issue by zigzag95** [Microsoft/PowerBI-CSharp#89]
Can't see Security namespace when using dotnet core with 4.6 framework

**Comment by ali-hamud** [comment]
There are no plans to update Microsoft.PowerBI.Core as it not needed any more after we moved from Azure Workspace Collection to Power BI Embedded.
Please consider moving to the new way of embedding powerbi, where you will have more features. To do so, please follow the link:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/

Please pay attention that "Non-Interactive" sign-in doesn't work in .Net core. For this, we will keep the following issue opened:
#116
