### ISSUE TITLE
Tile will not render

### ISSUE THREAD

**Issue by mooredd** [Microsoft/PowerBI-CSharp#9]
In embed-a-tile-into-an-app everything works fine with posting the loadTile message but then I get this error and the tile does not load.
Uncaught SyntaxError: Unexpected token u
k @ powerbivisualrenderer.min.js:2
$.ajax.success @ powerbivisualrenderer.min.js:1
j @ jquery-2.1.1.min.js:2
k.fireWith @ jquery-2.1.1.min.js:2
x @ jquery-2.1.1.min.js:4(anonymous function) @ jquery-2.1.1.min.js:4

**Comment by mooredd** [comment]
I was attempting to display a dashboard which was shared to me by someone else.  Once I created my own dashboard then it displayed as expected.

**Comment by kurtng** [comment]
I was receiving same error if my tiles contained more than one dashboard elements
