### ISSUE TITLE
Microsoft.PowerBI.Core 1.1.10 is not compatible with netcoreapp1.1 

### ISSUE THREAD

**Issue by jakubsvobodacz** [Microsoft/PowerBI-CSharp#95]
How can I embed powerbi in my .net core 1.1 app? When trying to deploy the Microsoft.PowerBI.Core package it throws this error.

Package Microsoft.PowerBI.Core 1.1.10 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1)

**Comment by ali-hamud** [comment]
There are no plans to update Microsoft.PowerBI.Core as it not needed any more after we moved from Azure Workspace Collection to Power BI Embedded.
Please consider moving to the new way of embedding powerbi, where you will have more features. To do so, please follow the link:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/

Please pay attention that "Non-Interactive" sign-in doesn't work in .Net core. For this, we will keep the following issue opened:
https://github.com/Microsoft/PowerBI-CSharp/issues/116
